-- Generated by nwg-displays on 2026-07-05 at 13:35:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1366x768@59.79",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1366x768@59.79",
    position = "1366x0",
    scale = 1.0
})
